# Generated by Django 5.1.4 on 2025-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_studentdue_collected_by_studentdue_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
