# Generated by Django 5.1.4 on 2025-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_studentdue_updated_at'),
    ]

    operations = [
    ]
