# Generated by Django 5.1.4 on 2025-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20250906_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentdue',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
